### ISSUE TITLE
"An error occurs when trying to open .docx file(.doc is ok) documents using OnlyOffice in Odoo 16 Enterprise edition."

### ISSUE THREAD

**Issue by orzzorzz** [ONLYOFFICE/onlyoffice_odoo#10]
http://192.168.2.179:8069/onlyoffice/editor/272
500: Internal Server Error
[跟踪](http://192.168.2.179:8069/onlyoffice/editor/272#error_traceback)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1723, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/onlyoffice_odoo/controllers/controllers.py", line 87, in render_editor
    return request.render("onlyoffice_odoo.onlyoffice_editor", self.prepare_editor_values(attachment, access_token))
  File "/usr/lib/python3/dist-packages/odoo/addons/onlyoffice_odoo/controllers/controllers.py", line 165, in prepare_editor_values
    "key": str(data["id"]) + data["checksum"],
TypeError: can only concatenate str (not "bool") to str

**Comment by LinneyS** [comment]
Fixed at 2a3670ad55a64dbee98b2049d8adbf7f82660e27

**Comment by orzzorzz** [comment]
thanks

**Comment by orzzorzz** [comment]
@LinneyS .xlsx is ok
but  open .docx  show this
500: Internal Server Error
[跟踪](http://192.168.2.179:8069/onlyoffice/editor/232#error_traceback)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1723, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/onlyoffice_odoo/controllers/controllers.py", line 87, in render_editor
    return request.render("onlyoffice_odoo.onlyoffice_editor", self.prepare_editor_values(attachment, access_token))
  File "/usr/lib/python3/dist-packages/odoo/addons/onlyoffice_odoo/controllers/controllers.py", line 165, in prepare_editor_values
    "key": str(data["id"]) + str(data["checksum"]),
TypeError: can only concatenate str (not "bool") to str
